"""log_importeds table

Revision ID: 552caa2b2519
Revises: 
Create Date: 2018-12-05 19:16:15.071723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '552caa2b2519'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_imported',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('sender_address', sa.String(length=255), nullable=True),
    sa.Column('recipient_address', sa.String(length=255), nullable=True),
    sa.Column('recipient_count', sa.Integer(), nullable=True),
    sa.Column('return_path', sa.String(length=255), nullable=True),
    sa.Column('client_hostname', sa.String(length=255), nullable=True),
    sa.Column('client_ip', sa.String(length=100), nullable=True),
    sa.Column('server_hostname', sa.String(length=255), nullable=True),
    sa.Column('server_ip', sa.String(length=100), nullable=True),
    sa.Column('original_client_ip', sa.String(length=100), nullable=True),
    sa.Column('original_server_ip', sa.String(length=100), nullable=True),
    sa.Column('event_id', sa.String(length=50), nullable=True),
    sa.Column('total_bytes', sa.Integer(), nullable=True),
    sa.Column('connector_id', sa.String(length=50), nullable=True),
    sa.Column('message_subject', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_imported_id'), 'log_imported', ['id'], unique=False)
    op.create_index(op.f('ix_log_imported_sender_address'), 'log_imported', ['sender_address'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_imported_sender_address'), table_name='log_imported')
    op.drop_index(op.f('ix_log_imported_id'), table_name='log_imported')
    op.drop_table('log_imported')
    # ### end Alembic commands ###
